name: Build ZMK firmware

on:
  push:
    branches: [prime]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Checkout repository
        timeout-minutes: 5
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Install Nix
        timeout-minutes: 5
        uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Use Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: rrvsh
          extraPullNames: nix-community,hyprland,yazi,cuda-maintainers
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build firmware with Just
        run: nix develop --command just build

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: result/*.uf2
