name: Build ZMK firmware

on:
  push:
    branches:
      - prime
    paths:
      - "config/**"
      - "flake.nix"
      - "flake.lock"
      - "Justfile"
      - ".github/workflows/build-zmk.yaml"
  pull_request:
    paths:
      - "config/**"
      - "flake.nix"
      - "flake.lock"
      - "Justfile"
      - ".github/workflows/build-zmk.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build firmware with Just
        run: nix develop --command just build

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: result/*.uf2
